CREATE TABLE public.SALE (
	ID_SALE INTEGER NOT NULL,
	SALE_DATE character varying(10) NOT NULL,
)
CREATE TABLE public.TYPE_SALE (
	ID_TYPE_SALE INTEGER NOT NULL,
	SALE_ITEM TINYINT CHECK (variavel BETWEEN 1 AND 3),
	ITEM_PRICE NUMERIC(10, 2)
)
CREATE TABLE public.SELLER (
	CPF_SELLER INTEGER NOT NULL,
	

)